#!/usr/bin/env python3
"""
Node.js Project Scaffold Generator
Creates a new Node.js/Express project with recommended structure and tooling.
"""

import argparse
import json
import sys
from pathlib import Path


def generate_structure(project_dir: Path, framework: str = "express"):
    """Generate Node.js project directory structure and files."""
    files = {
        "package.json": json.dumps({
            "name": project_dir.name,
            "version": "1.0.0",
            "description": f"A {framework} project",
            "main": "src/index.js",
            "scripts": {
                "dev": "nodemon src/index.js",
                "start": "node src/index.js",
                "build": "tsc",
                "lint": "eslint src/",
                "test": "jest",
                "format": "prettier --write src/"
            },
            "keywords": [],
            "author": "",
            "license": "ISC",
            "dependencies": {
                "express": "^4.21.0",
                "cors": "^2.8.5",
                "dotenv": "^16.4.5"
            },
            "devDependencies": {
                "nodemon": "^3.1.0",
                "eslint": "^9.0.0",
                "prettier": "^3.3.0",
                "jest": "^29.7.0"
            }
        }, indent=2),
        ".env.example": '''PORT=3000
NODE_ENV=development
DATABASE_URL=mongodb://localhost:27017/myapp
JWT_SECRET=your-jwt-secret-here
''',
        ".gitignore": '''node_modules/
dist/
build/
.env
.env.local
*.log
.DS_Store
coverage/
.nyc_output/
''',
        "README.md": f"""# {project_dir.name}

A {framework} project.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
""",
    }

    if framework == "express":
        files["src/index.js"] = '''const express = require("express");
const cors = require("cors");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Routes
app.get("/", (req, res) => {
  res.json({ message: "Hello World" });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
'''
        files["src/routes/index.js"] = '''const express = require("express");
const router = express.Router();

router.get("/", (req, res) => {
  res.json({ status: "ok" });
});

module.exports = router;
'''
        files[".eslintrc.js"] = '''module.exports = {
  root: true,
  env: { node: true, es2021: true },
  parserOptions: { ecmaVersion: 2021 },
  extends: ["eslint:recommended"],
  rules: {
    "no-unused-vars": "warn",
    "prefer-const": "error",
  },
};
'''
        files[".prettierrc"] = '{"semi": true, "trailingComma": "es5", "singleQuote": true, "printWidth": 100}'

    elif framework == "nextjs":
        files["package.json"] = json.dumps({
            "name": project_dir.name,
            "version": "0.1.0",
            "private": True,
            "scripts": {
                "dev": "next dev",
                "build": "next build",
                "start": "next start",
                "lint": "next lint"
            },
            "dependencies": {
                "next": "^15.0.0",
                "react": "^19.0.0",
                "react-dom": "^19.0.0"
            },
            "devDependencies": {
                "@types/node": "^22.0.0",
                "@types/react": "^19.0.0",
                "typescript": "^5.6.0",
                "eslint": "^9.0.0",
                "eslint-config-next": "^15.0.0"
            }
        }, indent=2)

        files["next.config.js"] = '''/** @type {import("next").NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
'''
        files["tsconfig.json"] = json.dumps({
            "compilerOptions": {
                "lib": ["dom", "dom.iterable", "esnext"],
                "allowJs": True,
                "skipLibCheck": True,
                "strict": True,
                "noEmit": True,
                "esModuleInterop": True,
                "module": "esnext",
                "moduleResolution": "bundler",
                "resolveJsonModule": True,
                "isolatedModules": True,
                "jsx": "preserve",
                "incremental": True,
                "plugins": [{"name": "next"}],
                "paths": {"@/*": ["./*"]}
            },
            "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
            "exclude": ["node_modules"]
        }, indent=2)

        (project_dir / "src/app").mkdir(parents=True, exist_ok=True)
        files["src/app/layout.tsx"] = '''import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "{project_name}",
  description: "Generated by dev-environment-setup",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
'''
        files["src/app/page.tsx"] = '''export default function Home() {
  return (
    <main>
      <h1>Welcome to {project_name}</h1>
    </main>
  );
}
'''

    # Write all files
    for path, content in files.items():
        full_path = project_dir / path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)

    # Create src directory
    (project_dir / "src").mkdir(exist_ok=True)
    (project_dir / "src" / "routes").mkdir(exist_ok=True)
    (project_dir / "src" / "controllers").mkdir(exist_ok=True)
    (project_dir / "src" / "middleware").mkdir(exist_ok=True)
    (project_dir / "src" / "utils").mkdir(exist_ok=True)

    # Create test directory
    (project_dir / "test").mkdir(exist_ok=True)
    (project_dir / "test" / "setup.js").write_text('''// Test setup
const dotenv = require("dotenv");
dotenv.config({ path: ".env.test" });
''')

    print(f"[+] {framework.title()} 项目脚手架已生成: {project_dir}")
    print(f"    下一步: cd {project_dir} && npm install && npm run dev")


def main():
    parser = argparse.ArgumentParser(description="Node.js 项目脚手架生成器")
    parser.add_argument("project_name", help="项目名称")
    parser.add_argument("--dir", default=".", help="目标目录（默认当前目录）")
    parser.add_argument(
        "--framework",
        choices=["express", "nextjs"],
        default="express",
        help="框架类型（默认: express）",
    )
    args = parser.parse_args()

    project_dir = Path(args.dir) / args.project_name
    if project_dir.exists():
        print(f"[!] 目录已存在: {project_dir}")
        sys.exit(1)

    generate_structure(project_dir, args.framework)


if __name__ == "__main__":
    main()
